#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
echo "[1/5] checking critical files"
test -f "$ROOT/js/firebase-config.js"
test -f "$ROOT/firestore.rules"
test -f "$ROOT/storage.rules"
test -f "$ROOT/functions/index.js"
test -f "$ROOT/service-worker.js"
echo "[2/5] checking version sync"
grep -q "2.1.0" "$ROOT/js/firebase-config.js"
grep -q "2.1.0" "$ROOT/README.md"
echo "[3/5] checking docs"
test -f "$ROOT/docs/STAGING_TEST_PACK.md"
test -f "$ROOT/docs/UAT_FIX_PACK.md"
test -f "$ROOT/docs/UAT_SIGNOFF_TEMPLATE.md"
echo "[4/5] checking phase-A production checklist"
test -f "$ROOT/docs/PRODUCTION_CHECKLIST.md"
echo "[5/5] basic smoke checks passed"
